[build]
publish = "public"
command = "echo No build required"

[[redirects]]
from = "/r/*"
to = "/redirect.html"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/ads.txt"
status = 200
force = true

[[Redirect]] 
from = "/https://srv.adstxtmanager.com/73084/urly.lat"
to "//ads.txt" 
301

[functions]
directory = "functions"
