[build]
publish = "public"
command = "echo No build required"

[[redirects]]
from = "/r/*"
to = "/redirect.html"
status = 200
force = true

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[[redirects]]
  from = "/ads.txt"
  to = "https://srv.adstxtmanager.com/73084/urly.lat"
  status = 301
  force = true
  headers = {X-From = "Netlify"}

[functions]
directory = "functions"
